import js from '@eslint/js';
import globals from 'globals';

export default [
  {
    ignores: ['dist/', 'dist-large/', '.build-cache/', '.wrangler/', '.venv*/', 'clients/*/dist/'],
  },
  js.configs.recommended,
  {
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
      reportUnusedInlineConfigs: 'error',
    },
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
    },
    rules: {
      'array-callback-return': 'error',
      'consistent-return': 'error',
      curly: ['error', 'all'],
      'default-case-last': 'error',
      eqeqeq: ['error', 'always'],
      'no-caller': 'error',
      'no-console': 'error',
      'no-constructor-return': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-implicit-coercion': ['error', { allow: ['!!'] }],
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-multi-assign': 'error',
      'no-new': 'error',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-object-constructor': 'error',
      'no-param-reassign': 'error',
      'no-promise-executor-return': 'error',
      'no-proto': 'error',
      'no-return-assign': ['error', 'always'],
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-shadow': ['error', { hoist: 'all' }],
      'no-template-curly-in-string': 'error',
      'no-throw-literal': 'error',
      'no-undef-init': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unreachable-loop': 'error',
      'no-unused-expressions': 'error',
      'no-unused-vars': ['error', { args: 'all', caughtErrors: 'all', ignoreRestSiblings: false }],
      'no-use-before-define': ['error', { functions: false, classes: true, variables: true }],
      'no-useless-call': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-concat': 'error',
      'no-useless-rename': 'error',
      'no-useless-return': 'error',
      'no-var': 'error',
      'object-shorthand': ['error', 'properties'],
      'prefer-const': 'error',
      'prefer-promise-reject-errors': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      radix: 'error',
      strict: ['error', 'safe'],
      yoda: 'error',
    },
  },
  {
    files: ['functions/**/*.js'],
    languageOptions: { globals: globals.serviceworker },
  },
  {
    files: ['functions/**/*.test.mjs'],
    languageOptions: { globals: globals.node },
  },
  {
    files: ['scripts/**/*.mjs', 'eslint.config.mjs'],
    languageOptions: { globals: globals.node },
  },
  {
    files: ['scripts/**/*.mjs'],
    rules: { 'no-console': 'off' },
  },
  {
    files: ['pipeline/publicdata/static/site.js'],
    languageOptions: { sourceType: 'script', globals: globals.browser },
  },
  {
    files: ['pipeline/publicdata/static/explorer.js', 'explorer/**/*.js'],
    languageOptions: { globals: globals.browser },
  },
];
